In [184]:
# -*- coding: utf-8 -*-
import pandas as pd
import re
import numpy as np
import cPickle

In [185]:
df = pd.read_csv('data/Yimi600training.csv', usecols=['顾客','坐席','是否违规'], sep=',')

In [86]:
df = pd.read_csv('data/mbu.csv', usecols=['Rating','Review'], sep=',')

In [186]:
df=df.dropna()

In [187]:
df[:10]

顾客  \
36              没有。 对。 好 好好， 你们， 去 输 吗？ 我 联系 不上， 对 吧。   
37  喂， 哎 你好 你要 没 电 的 问题 是 吗？ 反正 我 在 支付宝 什么 委托 方 两千...   
38  喂， 不要， 骤增 英 说 你 妈 死了 是 吧 你 就要 干的 吗？ 如果你 妈妈 病 啊...   
39                                           楼。 对 然后。   
40  晚上。 嗯。 嗯 喂 你好。 哪位。 七， 很多 城市 那边。 啊 你说 你说。 大概 的 ...   
41  是不是 有病 啊 绿 源 万一 就是 人家。 也不 换 就是 添加， 一万。 电话 一天 文...   
42  南 街 华。 你 一个人。 哎 人家 扣 了， 啊。 你 媳妇 是不是 不一样 够了。 您 ...   
43  妈 你 再 来。 啊 儿子。 二二 八零。 没 没有 附近 的人 对不对 呀， 那 我就是 ...   
44  喂。 哎 你好。 短信 工作人员。 短信 或 哪 女士 您 所 限 行了 我 只 是个 联系...   
45  喂， 反正， 然后然后， 请问 是 高 磊 的 附近 呢。 我是 向 别的 了 这个 明 白...   

                                                   坐席  是否违规  
36  o， 请问 一下 您 自己 跟 文 金 霞 女士 吗？ 张家界 还在 甘肃 是 吗 甘肃 平...     1  
37  一 百万。 五 不好意思 或者 您 下次 送 你 给我 分到 等。 我 等一下。 我 怎么 ...     0  
38  一 笔 是不是 没 打过 你 发给。 一百 二 十三 块钱。 关于 打电话。 一个 都都 跑...     1  
39                  一。 二月 营运 中 现在 工艺 精制 而成 喂， 对 对， 嗯。     0  
40  一。 喂， 谢谢， 嗯 喂 你好。 喂。 而 心 魔 吗？ 哎 你好 我们 是 邮政银行 为...     0  
41  一万。 你 你 那你 其他 有 什么 关系 日 老是 打 给我 那个 你你你？ 给你 都给 ...     1  
42  一个 狗 的你 这 样子 就 慢 您 随之 吃了 嘛 就原来 新 打了 几分钟 到账 上 完...     1  
43  一个人 玩 是不是 这么 没事 我 就 打了 怎么了， 是 哪个 怎么了 你能 拿 我 怎么...     1  
44  一会儿。 哦 你在 拿 短信 通知 到我 吗？ 啊， 呃 是不是 短信 是 哪里， 啊， 说...     1  
45  一半 啊。 基本 找 他 呀 你 怎么 找到 我的 号码 呢。 嗯， 他 留下 他 留 的 ...     1

In [188]:
x=df.values

In [154]:
np.random.shuffle(x)

In [189]:
x[:10]

array([['\xe6\xb2\xa1\xe6\x9c\x89\xe3\x80\x82 \xe5\xaf\xb9\xe3\x80\x82 \xe5\xa5\xbd \xe5\xa5\xbd\xe5\xa5\xbd\xef\xbc\x8c \xe4\xbd\xa0\xe4\xbb\xac\xef\xbc\x8c \xe5\x8e\xbb \xe8\xbe\x93 \xe5\x90\x97\xef\xbc\x9f \xe6\x88\x91 \xe8\x81\x94\xe7\xb3\xbb \xe4\xb8\x8d\xe4\xb8\x8a\xef\xbc\x8c \xe5\xaf\xb9 \xe5\x90\xa7\xe3\x80\x82',
        'o\xef\xbc\x8c \xe8\xaf\xb7\xe9\x97\xae \xe4\xb8\x80\xe4\xb8\x8b \xe6\x82\xa8 \xe8\x87\xaa\xe5\xb7\xb1 \xe8\xb7\x9f \xe6\x96\x87 \xe9\x87\x91 \xe9\x9c\x9e \xe5\xa5\xb3\xe5\xa3\xab \xe5\x90\x97\xef\xbc\x9f \xe5\xbc\xa0\xe5\xae\xb6\xe7\x95\x8c \xe8\xbf\x98\xe5\x9c\xa8 \xe7\x94\x98\xe8\x82\x83 \xe6\x98\xaf \xe5\x90\x97 \xe7\x94\x98\xe8\x82\x83 \xe5\xb9\xb3 \xe5\x87\x89\xef\xbc\x9f \xe5\x9b\xa0\xe4\xb8\xba \xe5\x83\x8f \xe6\x88\x91\xe4\xbb\xac \xe8\xbf\x99 \xe8\xbf\x99\xe4\xb8\xaa \xe4\xb8\xa4\xe5\x8d\x83 \xe5\xa4\x9a \xe5\x9d\x97\xe9\x92\xb1 \xe8\xb4\xb7\xe6\xac\xbe \xe6\x88\x91\xe4\xbb\xac \xe8\xbf\x99\xe8\xbe\xb9 \xe5\x87\x86\xe5\xa4\x87 \xe4\xb8\x8a\xe9\x97\xa

In [190]:
s=x[:,1]

In [191]:
s[:10]

array(['o\xef\xbc\x8c \xe8\xaf\xb7\xe9\x97\xae \xe4\xb8\x80\xe4\xb8\x8b \xe6\x82\xa8 \xe8\x87\xaa\xe5\xb7\xb1 \xe8\xb7\x9f \xe6\x96\x87 \xe9\x87\x91 \xe9\x9c\x9e \xe5\xa5\xb3\xe5\xa3\xab \xe5\x90\x97\xef\xbc\x9f \xe5\xbc\xa0\xe5\xae\xb6\xe7\x95\x8c \xe8\xbf\x98\xe5\x9c\xa8 \xe7\x94\x98\xe8\x82\x83 \xe6\x98\xaf \xe5\x90\x97 \xe7\x94\x98\xe8\x82\x83 \xe5\xb9\xb3 \xe5\x87\x89\xef\xbc\x9f \xe5\x9b\xa0\xe4\xb8\xba \xe5\x83\x8f \xe6\x88\x91\xe4\xbb\xac \xe8\xbf\x99 \xe8\xbf\x99\xe4\xb8\xaa \xe4\xb8\xa4\xe5\x8d\x83 \xe5\xa4\x9a \xe5\x9d\x97\xe9\x92\xb1 \xe8\xb4\xb7\xe6\xac\xbe \xe6\x88\x91\xe4\xbb\xac \xe8\xbf\x99\xe8\xbe\xb9 \xe5\x87\x86\xe5\xa4\x87 \xe4\xb8\x8a\xe9\x97\xa8 \xe5\x8e\xbb \xe6\x8b\xbf \xe8\xbf\x99\xe4\xb8\xaa \xe6\xac\xbe\xe9\xa1\xb9 \xe5\xa6\x82\xe6\x9e\x9c \xe6\x82\xa8 \xe5\x88\x9a\xe5\x88\x9a \xe6\x9c\x89 \xe8\x81\x94\xe7\xb3\xbb \xe9\xba\xbb\xe7\x83\xa6 \xe6\x82\xa8 \xe5\x86\x8d\xe8\xaf\xb4 \xe4\xb8\x80\xe4\xb8\x8b \xe4\xbb\x8a\xe5\xa4\xa9 \xe4\xb8\x8b\xe5\x8d\x88 \xe4\xbc

In [192]:
sent=[]
vocab = {}

In [193]:
def clean_str(string):
    """
    Tokenization/string cleaning for all datasets except for SST.
    Every dataset is lower cased except for TREC
    """
    #string = re.sub(r"[^A-Za-z0-9(),\.!?]", " ", string)
    string = re.sub(r"[A-Za-z0-9(),\.!?]", " ", string)
    #string = re.sub(r"\'s", " \'s", string)
    string = re.sub(r"e\.g\.,", " ", string)
    string = re.sub(r"a\.k\.a\.", " ", string)
    string = re.sub(r"i\.e\.,", " ", string)
    string = re.sub(r"i\.e\.", " ", string)
    #string = re.sub(r"\'ve", " \'ve", string)
    #string = re.sub(r"\'", "", string)
    #string = re.sub(r"\'re", " \'re", string)
    #string = re.sub(r"\'d", " \'d", string)
    #string = re.sub(r"\'ll", " \'ll", string)
    string = re.sub(r",", "", string)
    #string = re.sub(r",", " , ", string)
    string = re.sub(r"br", "", string)
    string = re.sub(r"!", "", string)
    #string = re.sub(r"!", " ! ", string)
    string = re.sub(r"\(", "", string)
    #string = re.sub(r"\(", " ( ", string)
    string = re.sub(r"\)", "", string)
    #string = re.sub(r"\)", " ) ", string)
    string = re.sub(r"\?", "", string)
    #string = re.sub(r"\?", " ? ", string)
    string = re.sub(r"\.", "", string)
    #string = re.sub(r"\.", " . ", string)
    string = re.sub(r"\s{2,}", " ", string)
    string = re.sub(r"u\.s\.", " us ", string)
    return string.strip().lower()

In [194]:
for i in s:
    temp = clean_str(i).split()
    sent.append(temp)
    t = set(temp)
    for word in t:
        if word in vocab:
            vocab[word] += 1
        else:
            vocab[word] = 1

In [195]:
#vocab

In [196]:
a='\xe8\xbf\x99\xe6\x9d\xa1\xe3\x80\x82'
print(a.decode('utf-8', 'ignore'))

这条。


In [197]:
ixtoword = {}

In [198]:
ixtoword[0] = 'END'
ixtoword[1] = 'UNK'
wordtoix = {}
wordtoix['END'] = 0
wordtoix['UNK'] = 1
ix = 2

In [199]:
for w in vocab:
    wordtoix[w] = ix
    ixtoword[ix] = w
    ix += 1

In [200]:
ixtoword

{0: 'END',
 1: 'UNK',
 2: '\xe8\xbf\x99\xe6\x9d\xa1\xe3\x80\x82',
 3: '\xe4\xbd\xa0\xe5\x9c\xa8\xe3\x80\x82',
 4: '\xe6\x9c\x80\xe5\x90\x8e',
 5: '\xe5\xbd\x93\xe4\xb8\xad\xef\xbc\x8c',
 6: '\xe9\x9b\xa8\xe5\xad\xa3\xe3\x80\x82',
 7: '\xe5\xb7\xa5\xe5\x9c\xb0',
 8: '\xe5\x9c\x88',
 9: '\xe5\xbe\x8b\xe5\xb8\x88',
 10: '\xe9\x9a\x90\xe5\xbd\xa2\xef\xbc\x8c',
 11: '\xe5\x81\x9a\xe7\x94\x9f\xe6\x84\x8f\xe3\x80\x82',
 12: '\xe7\xa8\x8d\xe7\xad\x89\xe3\x80\x82',
 13: '\xe9\x81\x93\xe5\x9c\xb0\xe3\x80\x82',
 14: '\xe6\x88\x91\xe7\x9a\x84\xe8\xb4\xa6\xe6\x88\xb7\xef\xbc\x8c',
 15: '\xe5\x9c\x86',
 16: '\xe8\xbf\x98\xe5\x9c\xa8',
 17: '\xe5\xb0\x8f\xe6\x97\xb6\xe5\x80\x99\xef\xbc\x8c',
 18: '\xe7\xbb\x99\xe5\x87\xba',
 19: '\xe5\x90\x88\xe7\x90\x86',
 20: '\xe9\x9a\xbe\xe7\x9c\x8b',
 21: '\xe5\x9c\xb0',
 22: '\xe4\xbc\xa6\xe3\x80\x82',
 23: '\xe5\x9f\xba\xe5\xb1\x82\xe5\x8d\x95\xe4\xbd\x8d',
 24: '\xe5\x9c\xa8',
 25: '\xe6\x98\xaf\xe5\x9b\xa0\xe4\xb8\xba',
 26: '\xe5\x87\xa0\xe5\x88\x86\xe3\x80

In [201]:
def convert_word_to_ix(data):
    result = []
    for sent in data:
        temp = []
        for w in sent:
            if w in wordtoix:
                temp.append(wordtoix[w])
            else:
                temp.append(1)
        temp.append(0)
        result.append(temp)
    return result

In [202]:
train_sent = convert_word_to_ix(sent)

In [203]:
train_sent[:10]

[[7196,
  5057,
  9774,
  975,
  6147,
  8442,
  13935,
  13135,
  15397,
  7473,
  5911,
  7159,
  16,
  7588,
  15769,
  3502,
  7588,
  16554,
  12776,
  14457,
  6250,
  13723,
  6128,
  11469,
  15776,
  5019,
  1815,
  1062,
  13723,
  4905,
  13038,
  16146,
  11317,
  11897,
  11469,
  4406,
  1669,
  975,
  6122,
  264,
  5408,
  1620,
  975,
  3791,
  9774,
  9813,
  11327,
  12898,
  5392,
  14670,
  11191,
  14522,
  3774,
  3082,
  9979,
  14982,
  13157,
  5055,
  14398,
  24,
  14935,
  3122,
  10497,
  14033,
  15981,
  975,
  14267,
  0],
 [16185,
  9024,
  46,
  8475,
  16241,
  975,
  10326,
  4540,
  6951,
  1237,
  15196,
  8284,
  3775,
  15685,
  3775,
  1265,
  13490,
  6128,
  13516,
  3775,
  3775,
  12055,
  11957,
  10177,
  3753,
  9774,
  8048,
  15138,
  13723,
  6217,
  15557,
  3775,
  719,
  696,
  3502,
  14817,
  6147,
  1601,
  3072,
  693,
  13198,
  11469,
  8823,
  14973,
  12770,
  7907,
  13984,
  6940,
  0],
 [16185,
  1505,
  6831,
  3720,
  

In [204]:
train_y=x[:,2]

In [205]:
train_y[:10]

array([1, 0, 1, 0, 0, 1, 1, 1, 1, 1], dtype=object)

In [206]:
train_l=train_y

In [207]:
#train_l=[int(round(y)) for y in train_y]

In [208]:
train_l[:10]

array([1, 0, 1, 0, 0, 1, 1, 1, 1, 1], dtype=object)

In [209]:
train_lab=np.zeros((len(train_l),2))

In [210]:
for i,j in zip(range(len(train_lab)),train_l):
    train_lab[i][j-1]=1 

In [211]:
train_lab[:10]

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [212]:
len(train_sent)

3148

In [213]:
len(train_lab)

3148

In [214]:
l=len(train_lab)

In [215]:
s1=int(round(len(train_lab)*0.8))

In [216]:
s1

2518

In [217]:
s2=int(round(len(train_lab)*0.9))

In [218]:
s2

2833

In [219]:
train_x = train_sent[:s1]
train_y = train_lab[:s1]
val_x = train_sent[s1:s2]
val_y = train_lab[s1:s2]
test_x = train_sent[s2:]
test_y = train_lab[s2:]

In [220]:
cPickle.dump([train_x, val_x, test_x, train_y, val_y, test_y, wordtoix, ixtoword], open("yimi.p", "wb"))

In [221]:
len(vocab)

16600

In [222]:
train_y[:10]

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])